"""PDF report generation using reportlab."""
import io
import os
from datetime import datetime
from typing import Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

from backend.utils.logger import get_logger

logger = get_logger(__name__)

REPORTS_DIR = "reports"


def _ensure_reports_dir() -> str:
    os.makedirs(REPORTS_DIR, exist_ok=True)
    return REPORTS_DIR


def generate_pdf(report_data: dict, filename: Optional[str] = None) -> str:
    """Generate a PDF report and return the file path."""
    _ensure_reports_dir()

    if not filename:
        ts = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
        filename = f"report_{ts}.pdf"

    path = os.path.join(REPORTS_DIR, filename)
    buf = io.BytesIO()

    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=20 * mm, bottomMargin=20 * mm)
    styles = getSampleStyleSheet()
    story = []

    # Title
    title = report_data.get("event_name", "Event Report")
    story.append(Paragraph(f"<b>{title}</b>", styles["Title"]))
    story.append(Spacer(1, 6 * mm))

    # Decision badge
    decision = report_data.get("decision", "N/A").upper()
    color = "green" if decision == "APPROVED" else "red"
    story.append(Paragraph(f'Decision: <font color="{color}"><b>{decision}</b></font>', styles["Heading2"]))
    story.append(Spacer(1, 4 * mm))

    # Event metadata
    meta_rows = [
        ["Event Type", report_data.get("event_type", "")],
        ["Location", report_data.get("location", "")],
        ["Dates", report_data.get("dates", "")],
        ["Venue", report_data.get("venue_name", "")],
        ["Profitability Score", str(report_data.get("profitability_score", ""))],
        ["Risk Score", str(report_data.get("risk_score", ""))],
        ["Hotels Cheaper than Vendor", str(report_data.get("hotels_cheaper_count", ""))],
    ]
    meta_table = Table(meta_rows, colWidths=[60 * mm, 110 * mm])
    meta_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f0f0f0")),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, colors.HexColor("#fafafa")]),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 8 * mm))

    # Hotel comparison table
    hotels = report_data.get("hotels", [])
    if hotels:
        story.append(Paragraph("<b>Hotel Price Comparison</b>", styles["Heading3"]))
        story.append(Spacer(1, 3 * mm))

        header = ["Hotel", "Market $", "Vendor $", "Diff $", "Competitor $", "Available", "Risk"]
        rows = [header]
        for h in hotels:
            diff = h.get("price_difference", 0)
            rows.append([
                h.get("name", "")[:30],
                f"${h.get('market_price', 0):.2f}",
                f"${h.get('vendor_price', 0):.2f}",
                f"${diff:.2f}",
                f"${h.get('competitor_price', 0):.2f}",
                "Yes" if h.get("availability") else "No",
                str(h.get("risk_score", "")),
            ])

        col_widths = [55 * mm, 20 * mm, 20 * mm, 20 * mm, 25 * mm, 17 * mm, 13 * mm]
        hotel_table = Table(rows, colWidths=col_widths)
        hotel_table.setStyle(TableStyle([
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e40af")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8f8f8")]),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ("ALIGN", (1, 0), (-1, -1), "CENTER"),
        ]))
        story.append(hotel_table)
        story.append(Spacer(1, 6 * mm))

    # Footer
    story.append(Paragraph(
        f"Generated by 3atef — {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
        ParagraphStyle("footer", parent=styles["Normal"], fontSize=8, textColor=colors.HexColor("#888888")),
    ))

    doc.build(story)

    with open(path, "wb") as f:
        f.write(buf.getvalue())

    logger.info(f"pdf_generator: saved report to {path}")
    return path
